services:
  # Ambiente do Laboratorio
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      #- ./rabbitmq/data:/var/lib/rabbitmq
      #- ./rabbitmq/log:/var/log/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity --formatter json | tail -1 | grep -q '\"result\":\"ok\"'"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
  
  redis:
    image: redis/redis-stack
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379 
      - 8001:8001
    # volumes:
    #   - ./redis/data/:/data
    environment:
      REDIS_ARGS: --save 60 1000 --appendonly yes
      REDISTIMESERIES_ARGS: "RETENTION_POLICY=20"
    healthcheck:
      test: "redis-cli ping | grep -q PONG"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    ports:
      - 9000:9000
      - 9001:9001
    # MinIO é chato e precisa das senhas definidas em variavel de ambiente.
    env_file:
      - ./env_files/minio.env
    command: server /data --console-address ":9001"
    secrets:
      - usuario
      - senha

  # Containers com os programas auxiliares
  base_scripts:
    image: projeto_rabbitmq:projetoAda
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.12-bullseye
        RUN pip install minio pika redis
        RUN apt-get update && apt-get install curl --quiet --yes
    container_name: base_scripts
    volumes:
      - ./scripts/rabbitmq_connection.py:/scripts/rabbitmq_connection.py
      - ./scripts/minio_connection.py:/scripts/minio_connection.py
      - ./scripts/vazio.py:/scripts/app.py
    environment:
      PYTHONUNBUFFERED: 1
    entrypoint: python /scripts/app.py
    secrets:
      - usuario
      - senha

  criar_contas_redis:
    extends: base_scripts
    container_name: criar_contas_redis
    volumes:
      - ./scripts/criar_contas_redis.py:/scripts/app.py
    depends_on:
      redis:
        condition: service_healthy

  criar_ambiente_rabbitmq:
    extends: base_scripts
    container_name: criar_ambiente_rabbitmq
    volumes:
      - ./scripts/criar_ambiente_rabbitmq.py:/scripts/app.py
    depends_on:
      rabbitmq:
        condition: service_healthy
      criar_contas_redis:
        condition: service_completed_successfully

  producer_transacoes:
    extends: base_scripts
    container_name: producer_transacoes
    volumes:
      - ./scripts/producer_transacoes.py:/scripts/app.py
    depends_on:
      - criar_ambiente_rabbitmq

  consumer_transacoes:
    extends: base_scripts
    container_name: consumer_transacoes
    volumes:
      - ./scripts/consumer-transacoes.py:/scripts/app.py
    depends_on:
      - criar_ambiente_rabbitmq

  check_minio:
    extends: base_scripts
    container_name: check_minio
    depends_on:
      - minio
    healthcheck:
      test: curl --silent --head http://minio:9000/minio/health/live | grep -q 'HTTP/1.1 200 OK'
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
  
  criar_ambiente_minio:
    extends: base_scripts
    container_name: criar_ambiente_minio
    volumes:
      - ./scripts/criar_ambiente_minio.py:/scripts/app.py
    depends_on:
      - check_minio

  gera_relatorio:
    extends: base_scripts
    container_name: gera_relatorio
    volumes:
      - ./scripts/gera_relatorio.py:/scripts/app.py
    depends_on:
      - check_minio
      - rabbitmq
      - redis

secrets:
  usuario:
    file: ./secrets/usuario_padrao.txt
  senha:
    file: ./secrets/senha_padrao.txt
